/**
 * Vapi client (outbound voice) — lets the agent place a phone call to a business on the
 * owner's behalf and read back what happened. Three pieces of config: an API key, the
 * phone number to call FROM, and the saved "Concierge" assistant (its persona, manners,
 * guardrails, and patience tuning live on Vapi, set once via the dashboard/REST). Each
 * call only injects the per-call specifics (objective, what it may share, disclose flag).
 *
 * Everything is a plain REST call against api.vapi.ai. No SDK.
 */

import { restJson } from "../core/restJson";

const BASE = "https://api.vapi.ai";

export function vapiConfigured(): boolean {
  return !!(
    process.env.VAPI_API_KEY?.trim() &&
    process.env.VAPI_PHONE_NUMBER_ID?.trim() &&
    process.env.VAPI_ASSISTANT_ID?.trim()
  );
}

function key(): string {
  const k = process.env.VAPI_API_KEY?.trim();
  if (!k) throw new Error("Vapi isn't configured — set VAPI_API_KEY, VAPI_PHONE_NUMBER_ID, VAPI_ASSISTANT_ID.");
  return k;
}

async function vapi(method: "GET" | "POST", path: string, body?: unknown): Promise<any> {
  return restJson(`${BASE}${path}`, {
    method,
    headers: {
      Authorization: `Bearer ${key()}`,
      ...(body ? { "Content-Type": "application/json" } : {}),
    },
    ...(body ? { body: JSON.stringify(body) } : {}),
    errPrefix: `Vapi ${method} ${path}`,
  });
}

export interface PlaceCallInput {
  /** Destination in E.164, e.g. +13035551234. */
  to: string;
  /** What this call is trying to accomplish (drives the assistant for this one call). */
  objective: string;
  /** Info the assistant may share if asked — and only this. Optional. */
  details?: string;
  /** Whether to announce it's an AI calling on the owner's behalf. Default false. */
  disclose?: boolean;
  /**
   * Whether the assistant may use the owner's real name. Default FALSE — calls are
   * anonymous unless the task genuinely requires identity (an account lookup, a
   * reservation in their name).
   *
   * This has to be gated HERE rather than in the objective text: the first line out
   * of the assistant's mouth is spoken before any per-call instruction is read, so a
   * "don't give my name" objective can never win that race — the only thing that
   * suppresses the name is not sending it.
   */
  shareName?: boolean;
}

/**
 * The opening line and the message left on a machine. Both are sent as VARIABLES so
 * the name-gate reaches them.
 *
 * Not obvious, and the reason the first version of this gate did nothing: the greeting
 * is not generated by the model, it is spoken verbatim from the assistant's
 * `firstMessage` before the system prompt matters. If that field holds a literal name
 * (as it did) then gating the `callerName` variable suppresses the name everywhere
 * EXCEPT the one place the call always starts. `firstMessage` must therefore be a
 * variable too — see `config/vapi-assistant.json`.
 */
function openingLines(name: string | undefined): { greeting: string; voicemailLine: string } {
  if (!name) {
    return {
      greeting: "Hi, I have a quick question.",
      voicemailLine: "Hi, sorry I missed you — I'll try back another time. Thank you.",
    };
  }
  return {
    greeting: `Hi, I'm calling on behalf of ${name}.`,
    voicemailLine: `Hi, I'm calling on behalf of ${name}. They'll follow up directly. Thank you.`,
  };
}

/** Place an outbound call. Returns the Vapi call object (id + initial status). */
export async function placeCall(input: PlaceCallInput): Promise<any> {
  const ownerName = process.env.OWNER_NAME?.trim();
  const sharedName = input.shareName && ownerName ? ownerName : undefined;
  return vapi("POST", "/call", {
    phoneNumberId: process.env.VAPI_PHONE_NUMBER_ID!.trim(),
    assistantId: process.env.VAPI_ASSISTANT_ID!.trim(),
    customer: { number: input.to },
    assistantOverrides: {
      variableValues: {
        callerName: sharedName ?? "the caller",
        ...openingLines(sharedName),
        objective: input.objective,
        details: input.details?.trim() || "No additional details were provided for this call.",
        disclose: input.disclose ?? false,
      },
    },
  });
}

/** Fetch a call's current state (status, transcript, summary, cost, reason). */
export async function getCall(id: string): Promise<any> {
  return vapi("GET", `/call/${id}`, undefined);
}

const TERMINAL = new Set(["ended", "failed", "no-answer", "busy", "canceled"]);

export function isTerminal(status: string | undefined): boolean {
  return !!status && TERMINAL.has(status);
}

/** True only for a call that connected and ran to completion (vs. no-answer/busy/failed). */
export function isEnded(status: string | undefined): boolean {
  return status === "ended";
}

/**
 * Whether the post-call artifacts have actually landed. Vapi finalizes the
 * transcript, the analysis summary, and the real cost ASYNCHRONOUSLY — they lag
 * the `ended` status by a few seconds. The call object at first-`ended` typically
 * has no transcript/summary and cost 0, so we can't report on it yet.
 */
export function hasResults(call: any): boolean {
  const summary = call?.analysis?.summary || call?.summary;
  const transcript = call?.transcript || call?.artifact?.transcript;
  return !!(summary || transcript);
}

/** A human-readable digest of a (usually finished) call, for relaying back to the owner. */
export function summarize(call: any): string {
  const lines: string[] = [];
  lines.push(`status: ${call.status ?? "unknown"}${call.endedReason ? ` (${call.endedReason})` : ""}`);
  const summary = call.analysis?.summary || call.summary;
  if (summary) lines.push(`\nsummary:\n${summary}`);
  const transcript = call.transcript || call.artifact?.transcript;
  if (transcript) lines.push(`\ntranscript:\n${String(transcript).trim()}`);
  if (call.startedAt && call.endedAt) {
    const secs = Math.round((new Date(call.endedAt).getTime() - new Date(call.startedAt).getTime()) / 1000);
    lines.push(`\nduration: ${Math.floor(secs / 60)}m ${secs % 60}s`);
  }
  if (typeof call.cost === "number") lines.push(`cost: $${call.cost.toFixed(3)}`);
  return lines.join("\n");
}
